### ISSUE TITLE
Fix position of copyright banner

### ISSUE THREAD

**Issue by Creeparoo** [Veripeditus/veripeditus-web#3]
When typing something into a text area on a phone, the copyright banner moves over the virtual keyboard. That results in it blocking the view on the text area.
It also blocks the view on the register button and login button. This also only occurs on mobile devices.

**Comment by Natureshadow** [comment]
„partially fixes“

**Comment by Natureshadow** [comment]
„partially fixes“ ≠ „fixes“…
